apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pacman-kikd
    app.io/name: bingo
  name: pacman-kikd
  namespace: pacman
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pacman-kikd
    app.io/name: bingo
status:
  loadBalancer: {}
